apiVersion: v1
kind: Namespace
metadata:
  name: k8s-ecr-cred-autorenew
  labels:
    name: k8s-ecr-cred-autorenew
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8s-ecr-cred-autorenew
  name: svc-k8s-ecr-cred-autorenew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: k8s-ecr-cred-autorenew
  name: role-k8s-ecr-cred-autorenew
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["k8s-ecr-cred-autorenew"]
    verbs: ["get","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: k8s-ecr-cred-autorenew
  name: rb-k8s-ecr-cred-autorenew
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cr-k8s-ecr-cred-autorenew
subjects:
  - kind: ServiceAccount
    name: svc-k8s-ecr-cred-autorenew
    namespace: k8s-ecr-cred-autorenew